#!/bin/bash

# Configuration
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$BASE_DIR/.." && pwd)"
ARDIUM_LOCAL_PATH="$ROOT_DIR/_build/default/bin/main.exe"

if [ -f "$ARDIUM_LOCAL_PATH" ]; then
    ARDIUM_PATH="$ARDIUM_LOCAL_PATH"
else
    ARDIUM_PATH="arc"
fi

# Helper to get time in seconds
get_time() {
    python3 -c 'import time; print(time.time())'
}

print_header() {
    echo "## Topic $1"
    echo "| Language | Time (s) | Status | Output Preview |"
    echo "|:---|:---:|:---:|:---|"
}

run_test() {
    local LANG_NAME=$1
    local FILE=$2
    local DIR=$3
    local CMD_COMPILE=""
    local CMD_RUN=""
    local FILENAME=$(basename "$FILE")
    local NAME_NO_EXT="${FILENAME%.*}"
    local EMOJI=""
    
    cd "$DIR" || return

    case $LANG_NAME in
        "Ardium")
            EMOJI="⚡️"
            # Run the demo using JIT mode
            CMD_COMPILE="" # No explicit compile step for 'arc run'
            CMD_RUN="$ARDIUM_PATH run $FILENAME"
            ;;
        "Python")
            EMOJI="🐍"
            CMD_RUN="python3 $FILENAME"
            ;;
        "Go")
            EMOJI="🐹"
            CMD_COMPILE="go build -o $NAME_NO_EXT $FILENAME"
            CMD_RUN="./$NAME_NO_EXT"
            ;;
        "Rust")
            EMOJI="🦀"
            CMD_COMPILE="rustc $FILENAME -o $NAME_NO_EXT"
            CMD_RUN="./$NAME_NO_EXT"
            ;;
        "Swift")
            EMOJI="🍎"
            CMD_COMPILE="swiftc $FILENAME -o $NAME_NO_EXT"
            CMD_RUN="./$NAME_NO_EXT"
            ;;
        "Obj-C")
            EMOJI="🍏"
            CMD_COMPILE="clang $FILENAME -o $NAME_NO_EXT -framework Foundation -framework Cocoa"
            CMD_RUN="./$NAME_NO_EXT"
            ;;
    esac

    # Compile if needed
    if [ ! -z "$CMD_COMPILE" ]; then
        eval "$CMD_COMPILE" > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "| $EMOJI **$LANG_NAME** | - | ❌ Compile Error | See terminal |"
            return
        fi
    fi

    # Run
    local START=$(get_time)
    OUTPUT=$(eval "$CMD_RUN" 2>&1)
    local RET=$?
    local END=$(get_time)
    
    # Calculate duration
    DURATION=$(python3 -c "print(f'{($END - $START):.3f}')")

    if [ $RET -ne 0 ]; then
         echo "| $EMOJI **$LANG_NAME** | $DURATION | ❌ Runtime Error | See terminal |"
    else
        # Sanitize output for markdown table (replace newlines with space, pipe with I)
        CLEAN_OUT=$(echo "$OUTPUT" | tr '\n' ' ' | sed 's/|/I/g')
        if [ ${#CLEAN_OUT} -gt 60 ]; then
            CLEAN_OUT="${CLEAN_OUT:0:57}..."
        fi
        echo "| $EMOJI **$LANG_NAME** | $DURATION | ✅ Pass | \`$CLEAN_OUT\` |"
    fi
}

echo "# 🚀 Ardium Comparative Results"
echo "Generated by \`run_demos.sh\`"
echo ""

# Iterate Directories
for dir in "$BASE_DIR"/*; do
    if [ -d "$dir" ]; then
        dirname=$(basename "$dir")
        # Check if starts with digits and not Benchmark
        if [[ $dirname =~ ^[0-9] ]]; then
            topic_name=$(echo "$dirname" | cut -d'_' -f2-)
            topic_num=$(echo "$dirname" | cut -d'_' -f1)
            
            print_header "$topic_num: $topic_name"
            
            # Define language execution order: Ardium first, then sorted
            # To simplify, we just check specifically for each file type in order
            
            # Ardium
            # Skip GUI (09) and ML (10) for Ardium LITE runtime
            if [[ "$dirname" == *"09_GUI"* || "$dirname" == *"10_ML"* ]]; then
                echo "| ⚡️ **Ardium** | - | ⚠️ Skipped | GUI/ML not supported by LITE runtime |"
            else
                if ls "$dir"/*.ar 1> /dev/null 2>&1; then run_test "Ardium" "$dir"/*.ar "$dir"; fi
            fi
            # Go
            if ls "$dir"/*.go 1> /dev/null 2>&1; then run_test "Go" "$dir"/*.go "$dir"; fi
            # Obj-C
            if ls "$dir"/*.m 1> /dev/null 2>&1; then run_test "Obj-C" "$dir"/*.m "$dir"; fi
            # Python
            if ls "$dir"/*.py 1> /dev/null 2>&1; then run_test "Python" "$dir"/*.py "$dir"; fi
            # Rust
            if ls "$dir"/*.rs 1> /dev/null 2>&1; then run_test "Rust" "$dir"/*.rs "$dir"; fi
            # Swift
            if ls "$dir"/*.swift 1> /dev/null 2>&1; then run_test "Swift" "$dir"/*.swift "$dir"; fi
            
            echo ""
        fi
    fi
done
