(* lib/header_gen.ml *)
open Ast

let generate_header program =
  let buf = Buffer.create 1024 in
  Buffer.add_string buf "/* Generated by Ardium Compiler */\n\n";
  Buffer.add_string buf "#ifndef ARDIUM_GENERATED_H\n";
  Buffer.add_string buf "#define ARDIUM_GENERATED_H\n\n";
  Buffer.add_string buf "#include <stdint.h>\n\n";
  Buffer.add_string buf "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n";

  List.iter (function
    | Func { name; args; is_export = true; _ } ->
        Buffer.add_string buf (Printf.sprintf "int32_t %s(" name);
        let arg_strs = List.map (fun _ -> "int32_t") args in
        Buffer.add_string buf (String.concat ", " arg_strs);
        Buffer.add_string buf ");\n";
    | Import _ -> ()
    | _ -> ()
  ) program;

  Buffer.add_string buf "\n#ifdef __cplusplus\n}\n#endif\n";
  Buffer.add_string buf "#endif /* ARDIUM_GENERATED_H */\n";
  Buffer.contents buf

let save_header path program =
  let content = generate_header program in
  let oc = open_out path in
  output_string oc content;
  close_out oc
