#!/usr/bin/env python3
import os
import subprocess
import time
import sys
import glob

# Configuration
LANGUAGES = {
    "Ardium": {"ext": ".ar", "emoji": "⚡️"},
    "Python": {"ext": ".py", "emoji": "🐍"},
    "Go":     {"ext": ".go", "emoji": "🐹"},
    "Rust":   {"ext": ".rs", "emoji": "🦀"},
    "Swift":  {"ext": ".swift", "emoji": "🍎"},
    "Obj-C":  {"ext": ".m", "emoji": "🍏"},
}

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# 11_Benchmark is handled separately
DIRS = sorted([d for d in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR, d)) and d[0].isdigit() and not d.startswith("11")])

def run_command(cmd, cwd=None):
    try:
        # result = subprocess.run(cmd, cwd=cwd, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        # We capture stdout/stderr to suppress compilation noise unless error
        result = subprocess.run(cmd, cwd=cwd, shell=True, capture_output=True, text=True)
        if result.returncode != 0:
            return False, result.stderr
        return True, result.stdout
    except Exception as e:
        return False, str(e)

def compile_and_run(lang, file_path, cwd):
    filename = os.path.basename(file_path)
    name_no_ext = os.path.splitext(filename)[0]
    
    cmd_compile = ""
    cmd_run = ""
    
    if lang == "Ardium":
        # Assumed standard installation or local build
        # We try local build first
        arc_path = "../../_build/default/bin/main.exe"
        if not os.path.exists(os.path.join(cwd, arc_path)):
            arc_path = "arc" # System installed
            
        cmd_compile = f"{arc_path} build {filename} -o {name_no_ext}"
        cmd_run = f"./{name_no_ext}"
        
    elif lang == "Python":
        cmd_run = f"python3 {filename}"
        
    elif lang == "Go":
        cmd_compile = f"go build -o {name_no_ext} {filename}"
        cmd_run = f"./{name_no_ext}"
        
    elif lang == "Rust":
        cmd_compile = f"rustc {filename} -o {name_no_ext}"
        cmd_run = f"./{name_no_ext}"
        
    elif lang == "Swift":
        cmd_compile = f"swiftc {filename} -o {name_no_ext}"
        cmd_run = f"./{name_no_ext}"
        
    elif lang == "Obj-C":
        cmd_compile = f"clang {filename} -o {name_no_ext} -framework Foundation -framework Cocoa"
        cmd_run = f"./{name_no_ext}"

    # Compile
    if cmd_compile:
        ok, out = run_command(cmd_compile, cwd)
        if not ok:
            return None, "❌ Compile Error", "See terminal"

    # Run
    start = time.time()
    ok, out = run_command(cmd_run, cwd)
    end = time.time()
    
    if not ok:
        return None, "❌ Runtime Error", "See terminal"
    
    output_preview = out.strip().replace("\n", " ").replace("|", "I")
    if len(output_preview) > 60:
        output_preview = output_preview[:57] + "..."
        
    return (end - start), "✅ Pass", output_preview

def main():
    print(f"# 🚀 Ardium Comparative Results")
    print(f"Generated by `run_demos.py`\n")
    
    for d in DIRS:
        topic_name = d.split("_", 1)[1] if "_" in d else d
        print(f"## Topic {d[:2]}: {topic_name}")
        print(f"| Language | Time (s) | Status | Output Preview |")
        print(f"|:---|:---:|:---:|:---|")
        
        full_dir = os.path.join(BASE_DIR, d)
        
        # Sort languages: Ardium first, then others alphabetically
        sorted_langs = sorted(LANGUAGES.keys(), key=lambda x: (0 if x == "Ardium" else 1, x))
        
        for lang_name in sorted_langs:
            config = LANGUAGES[lang_name]
            files = glob.glob(os.path.join(full_dir, "*" + config["ext"]))
            if not files:
                # print(f"| {config['emoji']} {lang_name} | - | ⚠️ Missing | - |")
                continue
                
            f = files[0]
            elapsed, status, out_preview = compile_and_run(lang_name, f, full_dir)
            
            # Format time
            time_str = f"{elapsed:.3f}" if isinstance(elapsed, float) else "-"
            
            print(f"| {config['emoji']} **{lang_name}** | {time_str} | {status} | `{out_preview}` |")
        
        print(f"\n")

if __name__ == "__main__":
    main()
