(library
 (name ardium_core)
 (public_name ardium)
 (libraries core str llvm llvm.analysis llvm.bitwriter llvm.target llvm.executionengine llvm.all_backends ctypes)
 (foreign_stubs (language c) (names jit_stubs))
 (c_library_flags (-L%{workspace_root}/runtime/build -lardium -Wl,-rpath,%{workspace_root}/runtime/build)))

(menhir
 (modules parser))

(ocamllex
 (modules lexer))
