/* Generated by Ardium Compiler */

#ifndef ARDIUM_GENERATED_H
#define ARDIUM_GENERATED_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t get_magic_number();
int32_t print_status(int32_t);
int32_t main();

#ifdef __cplusplus
}
#endif
#endif /* ARDIUM_GENERATED_H */
