(lang dune 3.0)
(using menhir 2.1)
(name ardium)

(generate_opam_files true)

(source (github username/ardium))
(authors "Tirawat Nantamas")
(maintainers "Tirawat Nantamas")

(package
 (name ardium)
 (synopsis "A Rust-like programming language")
 (description "Ardium Compiler written in OCaml")
 (depends
  (ocaml (>= 4.08))
  (dune (>= 3.0))
  (core (>= v0.14))
  (menhir (>= 20210419))
  (llvm (>= 10.0.0))
 )
)
