/* Generated by Ardium Compiler */

#ifndef ARDIUM_GENERATED_H
#define ARDIUM_GENERATED_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t multiply(int32_t, int32_t);
int32_t add(int32_t, int32_t);

#ifdef __cplusplus
}
#endif
#endif /* ARDIUM_GENERATED_H */
