#!/bin/bash
set -e

export LC_ALL=C

# Location of files
COUNTER_FILE="packaging/build_counter"
VERSION_ML="lib/version.ml"
VERSION_TXT="packaging/current_version"

# Ensure packaging dir exists (if running from root)
mkdir -p packaging

# Generate Version
DATE_STR=$(date "+%d%b%y" | tr '[:lower:]' '[:upper:]')

if [ -f "$COUNTER_FILE" ]; then
    LAST_DATE=$(head -n 1 "$COUNTER_FILE")
    LAST_COUNT=$(tail -n 1 "$COUNTER_FILE")
    
    # Strip potential leading zeros to avoid octal interpretation (standard bash issue)
    # Actually, 10# forces decimal.
    
    if [ "$LAST_DATE" == "$DATE_STR" ]; then
        NEW_COUNT=$((10#$LAST_COUNT + 1))
    else
        NEW_COUNT=1
    fi
else
    NEW_COUNT=1
fi

# Save counter
printf "%s\n%03d" "$DATE_STR" "$NEW_COUNT" > "$COUNTER_FILE"

# Format Version String
RELEASE_VER=$(cat VERSION | tr -d '\n')
VERSION="${RELEASE_VER}+${DATE_STR}$(printf "%03d" "$NEW_COUNT")"

# 1. Output to OCaml file
echo "(* Generated by scripts/gen_version.sh *)" > "$VERSION_ML"
echo "let str = \"$VERSION\"" >> "$VERSION_ML"

# 2. Output to text file for make_pkg.sh
echo "$VERSION" > "$VERSION_TXT"

echo "🔹 Generated Output Version: $VERSION"
